
//Equipamientos en español, estos vienen de la api ExersiseDB
export const equipmentList = [
    { value: null, label: "Sin equipamiento" },
    { value: "assisted", label: "Asistido" },
    { value: "band", label: "Banda" },
    { value: "barbell", label: "Barra" },
    { value: "body weight", label: "Peso corporal" },
    { value: "bosu ball", label: "Bosu" },
    { value: "cable", label: "Cable" },
    { value: "dumbbell", label: "Mancuerna" },
    { value: "elliptical machine", label: "Máquina elíptica" },
    { value: "ez barbell", label: "Barra EZ" },
    { value: "hammer", label: "Hammer" },
    { value: "kettlebell", label: "Kettlebell" },
    { value: "leverage machine", label: "Máquina de palanca" },
    { value: "medicine ball", label: "Bola medicinal" },
    { value: "olympic barbell", label: "Barra olímpica" },
    { value: "resistance band", label: "Banda de resistencia" },
    { value: "roller", label: "Rodillo" },
    { value: "rope", label: "Cuerda" },
    { value: "skierg machine", label: "Máquina Skierg" },
    { value: "sled machine", label: "Máquina de trineo" },
    { value: "smith machine", label: "Máquina Smith" },
    { value: "stability ball", label: "Bola de estabilidad" },
    { value: "stationary bike", label: "Bicicleta estática" },
    { value: "stepmill machine", label: "Máquina Stepmill" },
    { value: "tire", label: "Neumático" },
    { value: "trap bar", label: "Barra trapecio" },
    { value: "upper body ergometer", label: "Ergómetro parte superior" },
    { value: "weighted", label: "Con peso" },
    { value: "wheel roller", label: "Rodillo de rueda" },
    { value: "other", label: "Otro" },
  ];